GET http://localhost:5001/api/sleepyhead
###
GET http://localhost:5001/api/sleepyhead/2
###
POST http://localhost:5001/api/sleepyhead HTTP/1.1
content-type: application/json

{
  "month": "2023-01-14",
  "start": "19.10",
  "end": "06.30",
  "amount": "11.20"
}
###
PUT http://localhost:5001/api/sleepyhead HTTP/1.1
content-type: application/json

{
  "id": 2,
  "month": "2023-11-01",
  "start": "19.12",
  "end": "08.12",
  "amount": "13.00"
}
###
DELETE http://localhost:5001/api/sleepyhead/5