CREATE TABLE sleepyhead(
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    month DATETIME DEFAULT NULL,
    `start` DECIMAL(8,2) DEFAULT NULL,
    end DECIMAL(8,2) DEFAULT NULL,
    amount DECIMAL(8,2) DEFAULT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);